FROM node:14.21.1-alpine
FROM nginx:stable-alpine
WORKDIR /usr/share/nginx/html
COPY main/build ./
RUN rm /etc/nginx/conf.d/default.conf
RUN mkdir material-kit-react
RUN mv static material-kit-react/
COPY nginx.conf /etc/nginx/conf.d
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

