FROM node:14.21.1-alpine
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY main/ ./app
COPY main/package.json ./
COPY main/package-lock.json ./
RUN npm config set timeout 6000000
RUN npm install --no-audit
RUN npm run build

FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]
