# Generated by Django 4.1.2 on 2022-10-31 17:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MissingPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calling_name', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=50)),
                ('year_of_birth', models.IntegerField(choices=[(1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)])),
                ('length', models.IntegerField(validators=[django.core.validators.MinValueValidator(60, 'The person cant be that small'), django.core.validators.MaxValueValidator(272, 'Is he the biggest person in the world??')])),
                ('hair_colour', models.SmallIntegerField(choices=[(0, 'Black'), (1, 'Very Dark Brown'), (2, 'Dark Brown'), (3, 'Medium Brown'), (4, 'Light Brown'), (5, 'Dark Blonde'), (6, 'Medium Blonde'), (7, 'Light Blonde')])),
                ('hair_length', models.SmallIntegerField(choices=[(0, 'short'), (1, 'medium'), (2, 'long'), (3, 'very long'), (4, 'extreme long')])),
                ('eye_colour', models.SmallIntegerField()),
                ('sex', models.CharField(choices=[(0, 'male'), (1, 'female')], max_length=2)),
                ('description', models.TextField()),
            ],
        ),
    ]
