# Generated by Django 4.1.2 on 2022-10-31 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missing_person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingperson',
            name='eye_colour',
            field=models.SmallIntegerField(choices=[(0, 'Blue'), (1, 'Brown'), (2, 'Gray'), (3, 'Hazel'), (4, 'Red')]),
        ),
    ]
