# Generated by Django 4.1.2 on 2022-10-31 19:47

from django.db import migrations, models
import django.db.models.deletion
import missing_person.models.missing_person


class Migration(migrations.Migration):

    dependencies = [
        ('missing_person', '0002_alter_missingperson_eye_colour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=missing_person.models.missing_person.image_custom_path)),
            ],
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='sex',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=2),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='images',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='missing_person.image'),
        ),
    ]
