# Generated by Django 4.1.2 on 2022-10-31 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missing_person', '0003_image_alter_missingperson_sex_missingperson_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missingperson',
            name='images',
        ),
        migrations.AddField(
            model_name='missingperson',
            name='images',
            field=models.ManyToManyField(to='missing_person.image'),
        ),
    ]
