# Generated by Django 4.1.2 on 2022-10-31 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missing_person', '0004_remove_missingperson_images_missingperson_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='origin',
            field=models.CharField(default='none', max_length=150),
            preserve_default=False,
        ),
    ]
