# Generated by Django 4.1.2 on 2022-10-31 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missing_person', '0005_missingperson_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='is_founded',
            field=models.BooleanField(default=False),
        ),
    ]
