# Generated by Django 4.1.2 on 2022-11-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missing_person', '0007_missingperson_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingperson',
            name='is_active',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
