# Generated by Django 4.1.2 on 2022-11-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missing_person', '0008_alter_missingperson_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingperson',
            name='images',
            field=models.ManyToManyField(blank=True, to='missing_person.image'),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
