# Generated by Django 4.1.2 on 2022-10-31 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile_iternal_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='iternal_currency',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
