# Generated by Django 4.1.2 on 2022-11-01 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_profile_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='iternal_currency',
            new_name='internal_currency',
        ),
    ]
