# Generated by Django 4.1.2 on 2022-11-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_iternal_currency_profile_internal_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=5)),
                ('country_name', models.CharField(max_length=80)),
                ('flag', models.CharField(help_text='https://emojipedia.org/flags/', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=5)),
                ('country_name', models.CharField(max_length=80)),
                ('flag', models.CharField(help_text='https://emojipedia.org/flags/', max_length=10)),
            ],
        ),
    ]
