# Generated by Django 4.1.2 on 2022-11-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_country_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='language',
            name='active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
