# Generated by Django 4.1.2 on 2022-11-17 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_link_header'),
    ]

    operations = [
        migrations.RenameField(
            model_name='header',
            old_name='liks',
            new_name='links',
        ),
    ]
