# Generated by Django 4.1.2 on 2022-11-18 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_liks_header_links'),
    ]

    operations = [
        migrations.RenameField(
            model_name='header',
            old_name='links',
            new_name='items',
        ),
        migrations.RenameField(
            model_name='link',
            old_name='url',
            new_name='href',
        ),
    ]
