# Generated by Django 4.1.2 on 2022-11-19 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_footer_menus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='menus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.header'),
        ),
    ]
