# Generated by Django 4.1.2 on 2022-11-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_footer_menus_footer_menus'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('description', models.CharField(max_length=100)),
                ('href', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='SubTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('description', models.CharField(max_length=100)),
                ('href', models.CharField(max_length=250)),
                ('dropdown', models.BooleanField()),
                ('collapse', models.ManyToManyField(to='main.subelement')),
            ],
        ),
        migrations.CreateModel(
            name='Tab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('columns', models.SmallIntegerField()),
                ('rows_per_column', models.SmallIntegerField()),
                ('href', models.CharField(max_length=250)),
                ('collapse', models.ManyToManyField(to='main.subtab')),
            ],
        ),
    ]
