# Generated by Django 4.1.2 on 2022-11-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_subelement_subtab_tab'),
    ]

    operations = [
        migrations.AddField(
            model_name='tab',
            name='icon',
            field=models.CharField(blank=True, help_text='https://mui.com/material-ui/material-icons/', max_length=100),
        ),
    ]
