# Generated by Django 4.1.2 on 2022-11-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_tab_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subelement',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='subelement',
            name='href',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='subtab',
            name='collapse',
            field=models.ManyToManyField(blank=True, to='main.subelement'),
        ),
        migrations.AlterField(
            model_name='subtab',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='subtab',
            name='href',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='tab',
            name='collapse',
            field=models.ManyToManyField(blank=True, to='main.subtab'),
        ),
        migrations.AlterField(
            model_name='tab',
            name='href',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
