# Generated by Django 4.1.2 on 2022-11-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_subelement_description_alter_subelement_href_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tab',
            name='columns',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tab',
            name='rows_per_column',
            field=models.SmallIntegerField(null=True),
        ),
    ]
