# Generated by Django 4.1.2 on 2022-11-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_tab_columns_alter_tab_rows_per_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tab',
            name='columns',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tab',
            name='rows_per_column',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
