# Generated by Django 4.1.2 on 2022-11-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_tab_columns_alter_tab_rows_per_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='subelement',
            name='route',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='subtab',
            name='route',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='tab',
            name='route',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
