# Generated by Django 4.1.3 on 2022-11-24 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_motto'),
    ]

    operations = [
        migrations.AddField(
            model_name='motto',
            name='languages',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.language'),
            preserve_default=False,
        ),
    ]
