# Generated by Django 4.1.2 on 2022-12-06 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0023_motto_languages"),
    ]

    operations = [
        migrations.AddField(
            model_name="footer",
            name="country",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.country",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="footer",
            name="language",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.language",
            ),
            preserve_default=False,
        ),
    ]
