# Generated by Django 4.1.2 on 2022-12-21 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_footer_country_footer_language'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brand',
            new_name='FooterBrand',
        ),
        migrations.RenameModel(
            old_name='Header',
            new_name='FooterHeader',
        ),
        migrations.RenameModel(
            old_name='Link',
            new_name='FooterLink',
        ),
        migrations.RenameModel(
            old_name='SubElement',
            new_name='NavBarSubElement',
        ),
        migrations.RenameModel(
            old_name='SubTab',
            new_name='NavBarSubTab',
        ),
        migrations.RenameModel(
            old_name='Tab',
            new_name='NavBarTab',
        ),
    ]
