# Generated by Django 4.1.2 on 2022-12-23 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_rename_brand_footerbrand_rename_header_footerheader_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbartab',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='navbartab',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.language'),
            preserve_default=False,
        ),
    ]
