# Generated by Django 4.1.2 on 2022-12-31 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_navbartab_country_navbartab_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motto',
            old_name='languages',
            new_name='language',
        ),
    ]
