# Generated by Django 4.1.2 on 2023-01-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_navbartab_options_navbartab_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbarsubelement',
            name='position',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='navbarsubtab',
            name='position',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
