# Generated by Django 4.1.2 on 2022-11-29 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basic", "0003_alter_article_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="url_title",
            field=models.TextField(default=".", editable=False),
            preserve_default=False,
        ),
    ]
