# Generated by Django 4.1.2 on 2022-12-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0005_remove_article_url_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='url_title',
            field=models.TextField(default=' ', editable=False),
            preserve_default=False,
        ),
    ]
