# Generated by Django 4.1.2 on 2023-01-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0006_article_url_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='group_pk',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
