# Generated by Django 4.1.2 on 2023-01-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0007_article_group_pk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={},
        ),
        migrations.RemoveField(
            model_name='article',
            name='url_title',
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='article',
            name='group_pk',
            field=models.SmallIntegerField(help_text='Same article in different language/country should have the same group_pk'),
        ),
    ]
