# Generated by Django 4.1.2 on 2022-10-31 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fields',
            new_name='Product',
        ),
    ]
