# Generated by Django 4.1.2 on 2022-10-31 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_fields_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
    ]
